### ISSUE TITLE
no method error while calculating probability

### ISSUE THREAD

**Issue by royaltm** [apohllo/c45#2]
```Traceback (most recent call last):
        3: from /R8/textplainer-engine/vendor/ruby/2.6.0/bundler/gems/c45-504c8549a40f/lib/c45/forest.rb:20:in `probability'
        2: from /R8/textplainer-engine/vendor/ruby/2.6.0/bundler/gems/c45-504c8549a40f/lib/c45/forest.rb:20:in `each'
        1: from /R8/textplainer-engine/vendor/ruby/2.6.0/bundler/gems/c45-504c8549a40f/lib/c45/forest.rb:21:in `block in probability'
/R8/textplainer-engine/vendor/ruby/2.6.0/bundler/gems/c45-504c8549a40f/lib/c45/node.rb:65:in `probability': undefined method `next_node' for #<C45::Node:0x00007f915810c1d8> (NoMethodError)
```
https://github.com/apohllo/c45/blob/master/lib/c45/node.rb#L65

this happened while trying to evaluate created model in the last step of textplainer training

**Comment by royaltm** [comment]
this is because the model has been created with Node instances and not the specialized version of it (e.g. ContinuousNode)
